Query:
  type: object
  config:
    fields:

      User:
        type: 'User'
        resolve: "@=resolver('User', [args['id']])"
        args:
          id:
            description: 'Resolve users by ID.'
            type: 'Int!'

      Users:
        type: '[User]'
        resolve: "@=resolver('Users')"

      Offers:
        type: '[Offer]'
        resolve: "@=resolver('Offers')"

      Countries:
        type: '[Country]'
        resolve: "@=resolver('Countries')"

      ShopCategories:
        type: '[ShopCategory]'
        resolve: "@=resolver('ShopCategories')"

      Shops:
        type: '[Shops]'
        resolve: "@=resolver('Shops')"

      CheckIfHaveShop:
        type: 'Boolean'
        resolve: "@=resolver('CheckIfHaveShop')"

      CheckIfConnected:
        type: 'Boolean'
        resolve: "@=resolver('CheckIfConnected')"

      CheckIfWCApiFilled:
        type: 'Boolean'
        resolve: "@=resolver('CheckIfWCApiFilled')"

      GenWcLink:
        type: 'String'
        resolve: "@=resolver('GenWcLink')"