User:
  type: object
  config:
    fields:
      id:
        type: 'Int!'
      username:
        type: 'String!'
      lastname:
        type: 'String'
      firstname:
        type: 'String'
      email:
        type: 'String!'
      birthday:
        type: 'String'
      offer:
        type: 'Offer'